
#H2 InMemory Database
spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:ekar-mysql}:${DATABASE_PORT:3306}/${DATABASE_NAME:ekardb}?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create
  devtools:
    livereload:
      enabled: false
    add-properties: false