#H2 InMemory Database
spring:
  datasource:
    url: jdbc:h2:mem:ekardb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
      enabled: true